#!/bin/bash
#Script for running wrf

#PBS -N Nov10_fire
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=10
#PBS -m bea
#PBS -M nmoisseeva@eos.ubc.ca
#PBS -l walltime=50:00:00

cd /home/moisseev/WRFV3/test/em_fire
echo "Running on `hostname`"
export OMP_NUM_THREADS=$PBS_NUM_PPN
echo "Starting run at: `date`"
#ulimit -uvs unlimited
/home/moisseev/WRFV3/test/em_fire/wrf.exe > log.txt
echo "Program finished with exit code $? at: `date`"

